### ISSUE TITLE
canSendSms make app crash unexpectedly

### ISSUE THREAD

**Issue by apm29** [rodydavis/plugins#46]
[flutter_sms]FlutterSms.canSendSMS() will crash when i run it on iOS, the log was `Unexpectedly found nil while unwrapping an Optional value` ,the cause is in the SwiftFlutterSmsPlugin 's handle function, `call.arguments as! [String:Any]; `and it seems that canSendSms didn't has argument...

**Comment by AppleEducate** [comment]
For now add a check too only run the call on android. I don't believe there is a way to check this on ios, am I right?

**Comment by rodydavis** [comment]
Is this still happening?

**Comment by rodydavis** [comment]
Please open an issue here: https://github.com/fluttercommunity/flutter_sms
