### ISSUE TITLE
Dart Firebase: is not a Flutter plugin?

### ISSUE THREAD

**Issue by pulyaevskiy** [rodydavis/plugins#49]
I got a little bit confused to find dart_firebase in a Flutter plugins repository. Since it's aiming to be fully cross-platform maybe it'd be worth for it to have its own repo.

**Comment by AppleEducate** [comment]
yes I am working on separating this from a mono repo to individual repos

**Comment by rodydavis** [comment]
This is now using submodules and separate repos. It now has its own repo  https://github.com/rodydavis/dart_firebase
