### ISSUE TITLE
flutter_sms - result received on android before sms is sent

### ISSUE THREAD

**Issue by OscarLinnarsson** [rodydavis/plugins#54]
Hi team! 

First I just wanna say I love the flutter_sms plugin. As google has a restrained policy for 3:e party apps sending sms I understand that this plugin won't be able to send sms without leaving the app, at least in the near future. 

In the app I'm building I need to iterate over a list of recipients and sending a tweaked version of the same sms to each and every one of them. My problem is that the result from the
 .sendSMS function is returned before the SMS has been sent/dismissed. As of now in my app the last number in the list will be opened and the SMS:es to the other people in the list I'm iterating over will be saved as drafts in my default SMS app. 

My problem would be solved if the .sendSMS method didn't return the result before knowing it or maybe if it could take a callback function and run it when the SMS is truly sent.

If this is something that has become broken since googles change in policy or if it isn't a feature as of now I would either way love if this feature could be added. 

Best regards!!

**Comment by ForGameProgrammer** [comment]
Can you share the code?
You need to use sendSms function inside Future so you can await. This might be the solution
