### ISSUE TITLE
Swift version issue - App not working after use this package

### ISSUE THREAD

**Issue by raipradeep** [rodydavis/plugins#70]
Hi When i use this package - app run from Xcode & also Android Studio not working.

1 warning generated. The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.

**Comment by raipradeep** [comment]
Hi How to fix this issue?? any solution ??

**Comment by craigomac** [comment]
```
[!] Unable to determine Swift version for the following pods:

- `app_review` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

I also see this issue. The trace is as above.
